audio_stop_sound(mDeathTheme);
audio_play_sound(mTheme, 1000, true);
window_set_size(display_get_width(), display_get_height());
surface_resize(application_surface, display_get_width(), display_get_height());
room_height = window_get_height();
room_width = window_get_width();
score = 0;
alarm[0] = room_speed * 0.5;
alarm[1] = room_speed * 0.5;
alarm[2] = room_speed * 5;
alarm[3] = room_speed * 2;
alarm[4] = room_speed * 10;
gameOver = false;
